name: Le premier

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
      
jobs:
  Hello:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test run
        run: echo Salut

      - name: Test checkout
        run: ls -al

      - run: env | sort

      # - name: Le test qui echoue
      #   run: exit(1)

  Test:
    needs: [Hello]
    runs-on: ubuntu-latest

    steps:
      - run: echo TOUT OK

  Deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo SUR SERVEUR



