name: Le premier

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
      
jobs:
  Hello:
    # defaults:
    #   run:
    #     working-directory: backend

    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Test run
        run: echo Salut

      - name: Test checkout
        run: ls -al

      - run: env | sort

      # - name: Le test qui echoue
      #   run: exit(1)

  Test:
    needs: [Hello]
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: toor
          MARIADB_DATABASE: test
          MARIADB_USER: test
          MARIADB_PASSWORD: test
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3                 

    env:
      BDD_HOST: 127.0.0.1
      BDD_NAME: test
      BDD_USER: test
      BDD_PASS: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Database Cnx Check
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port 3306 -u root -ptoor -e "SHOW DATABASES"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x


  Deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo SUR SERVEUR



