name: Le premier

on:
  push:
    branches: [main]
      
jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test run
        run: echo Salut




